### ISSUE TITLE
I Got an Error Using Wobble

### ISSUE THREAD

**Issue by Username778** [PhosCity/Aegisub-Scripts#3] opened 2023-04-16 22:54 UTC
It says, Failed to parse: btn, res = aegisub.dialog.display dialog, {"OK", "Cancel"}, {"ok": "OK", "cancel": "Cancel"}

**Comment by PhosCity** [comment] 2023-04-18 02:53
I cannot reproduce this error on my side neither in Linux nor in Windows. Can you give more information like which version of Aegisub are you using? Did you use dependency control to install the script?

**Comment by PhosCity** [comment] 2023-04-20 15:19
I now found out that this is caused when you use very old version of Aegisub. Please consider using a more recent version of Aegisub. The recommended version is this: https://github.com/arch1t3cht/Aegisub/releases

I'm closing this issue. If you encounter the issue even after using newer version of Aegisub, feel free to reopen this issue.

**Closed as completed by PhosCity** 2023-04-20 15:19 UTC
